# Generated by Django 3.2.18 on 2023-03-28 20:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Branchs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Districts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Form',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=50)),
                ('Dob', models.DateField()),
                ('Age', models.IntegerField()),
                ('Gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Others', 'Others')], default='Male', max_length=20)),
                ('Accounts', models.CharField(max_length=50)),
                ('Credit_card', models.BooleanField(default=False, verbose_name='Credit_card')),
                ('Debit_card', models.BooleanField(default=False, verbose_name='Debit_card')),
                ('Cheque_book', models.BooleanField(default=False, verbose_name='Cheque_book')),
                ('Branch', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='banksiteapp.branchs')),
                ('District', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='banksiteapp.districts')),
            ],
        ),
        migrations.AddField(
            model_name='branchs',
            name='District',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='banksiteapp.districts'),
        ),
    ]
