# Generated by Django 3.2.18 on 2023-03-30 18:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('banksiteapp', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Form',
        ),
    ]
